---
# GUI Applications Configuration Deployment

- name: Deploy WezTerm configuration
  copy:
    src: wezterm.lua
    dest: "{{ ansible_facts['env']['HOME'] }}/.wezterm.lua"
    mode: "0644"
    backup: true
